Algoritmo "7"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas Rafael
// Data atual  : 18/08/2021
var
 i, soma, num: inteiro

inicio

 num <- 1
 soma <- 0
 enquanto num <> 0 faca
 escreval("Digite um numero:")
 leia(num)
 soma <- soma + num
 fimenquanto
 escreval("O resultado da soma dos numeros digitados ?: ", soma)
fimalgoritmo